### ISSUE TITLE
Translation of comments

### ISSUE THREAD

**Issue by thanosvlo** [Tenglon/hyperbolic_action#2]
Hi, thanks for sharing the code for your paper, 
is it possible for you to translate the text comments in english ? Inline and in the notebook

**Comment by Tenglon** [comment]
Thanks for your attention, sorry for my negligence. 

I have updated the translation for dataset.py model.py and metric.py, 

pls let me know if further elaboration is needed.

**Comment by thanosvlo** [comment]
thanks
